package easy.tuto.myquizapplication;

public class QuestionAnswer {

    public static String question[] ={
            "Melakukan gerakkan tubuh secara terkoordinasi",
            "Melakukan koordinasi gerakan mata-kaki-tangan-kepala dalam meniru tarian",
            "Melakukan permainan fisik dengan aturan",
            "Terampil menggunakan tangan kanan dan kiri",
            "Melakukan kegiatan kebersihan diri",
            "Menggambar sesuai gagasannya",
            "Meniru bentuk",
            "Melakukan eksplorasi dengan berbagai alat makan dengan benar",
            "Menggunting sesuai pola",
            "Menempel gambar dengan tepat",
            "Mengekspresikan diri melalui gerakan menggambar secara rinci",
            "Berat badan sesuai usia",
            "Tinggi badan sesuai standar usia",
            "Beary badan sesuai dengan standar tinggi badan",
            "Lingkar kepala sesuai tingkat usia",
            "Menutup hidung dan mulut (misal, ketika batuk dan bersin)",
            "Membersihkan, dan membereskan tempat bermain",
            "Mengetahui situasi yang membahayakan diri",
            "Memahami tata cara menyebrang",
            "mengenal kebiasaan buruk bagi kesehatan (rokok, minuman keras)",
            "Menunjukkan aktivitas yang bersifat eksploratif dan menyelidik",
            "Memecahkan masalah sederhana dalam kehidudpan sehari-hari dengan cara yang fleksibel dan diterima sosial",
            "Menerapkan pengetahuan atau pengalaman dalam konteks yang baru",
            "Menunjukkan sikap kreatif dalam menyelesaikan masalah",
            "Mengenal perbedaan berdasarkan ukuran : (lebih dari) ; (kurang dari) ; dan (paling/ter)",
            "Menunjukkan inisiatif dalam memilih tema permainan",
            "Menyusun perencanaan kegiatan yang akan dilakukan",
            "Mengenal sebab-akibat tentang lingkungannya",
            "Mengklasifikasikan benda berdasarkan warna, bentuk, dan ukuran",
            "Mengklasifikasikan benda yang lebih banyak ke dalam kelompok yang sama atau kelompok yang sejenis, atau kelompok berpasangan yang lebih dari 2 variasi",
            "Mengenal pola ABCD-ABCD",
            "Mengurutkan benda berdasarkan ukuran dari paling kecil ke paling besar atau sebaliknya",
            "Menyatukan lambang bilangan 1-10",
            "Menggunakan lambang bilangan untuk menghitung",
            "Mencocokkan bilangan dengan lambang bilangan",
            "Mengenal berbagai macam lambang huruf vokal dan konsonal",
            "Merepresentasikan berbagai macam benda dalam bentuk gambar atau tulisan",
            "Mengerti beberapa perintah secara bersamaan",
            "Mengulang kalimat yang lebih kompleks",
            "Memahami aturan dalam suatu permainan",
            "Senang dan menghargai bacaan",
            "Senang dan menghargai bacaan",
            "Menjawab pertanyaan yang lebih kompleks",
            "Menyebutkan kelompok gambar yang memiliki bunyi yang sama",
            "Berkomunikasi secara lisan, memiliki perbedaharaan kata, serta mengenal simbol untuk persiapan membaca, menulis dan berhitung",
            "Menyusun kalimat sederhana dalam struktur lengkap (pokok kalimat-predikat-keterangan)",
            "Memiliki lebih banyak kata-kata untuk mengekpresikan ide pada orang lain",
            "Melanjutkan sebagian cerita/dongeng yang telah diperdengarkan",
            "Menunjukkan pemahaman konsep-konsep dalam buku cerita",
            "Menyebutkan simbol-simbol huruf yang dikenal",
            "Mengenai suara huruf awal dari nama benda-benda yang ada di sekitarnya",
            "Menyebutkan kelompok gambar yang memiliki bunyi/huruf awal yang sama",
            "Memahami hubungan antara bunyi dan bentuk huruf",
            "Membaca nama sendiri",
            "Menuliskan  nama sendiri",
            "Memahami arti kata dalam cerita",
            "Memperlihatkan kemampuan diri untuk menyesuaikan dengan situasi",
            "Memperlihatkan kehati-hatian  kepada orang yang belum dikenal (menumbuhkan kepercayaan pada orang dewasa yang tepat)",
            "Mengenal perasaan sendiri dan mengelolanya secara wajar (mengendalikan diri secara wajar)",
            "Tahu akan haknya",
            "Mentaati aturan kelas (kegiatan, aturan)",
            "Mengatur diri sendiri",
            "Bertanggung jawab atas perilakunya utnuk kebaikan diri sendiri",
            "Bermain dengan teman sebaya",
            "Mengetahui perasaan temannya dan merespon secara wajar",
            "Berbagi dengan orang lain",
            "Menghargai hak/pendapat/karya orang lain",
            "Menggunakan cara yang diterima secara sosial dalam menyelesaikan masalah (menggunakan pikiran untuk menyelesaikan masalah)",
            "Bersikap kooperatif dengan teman",
            "Menunjukkan sikap toleran",
            "Mengekspresikan emosi yang sesuai dengan kondisi yang ada (senang-sedih-antusias dsb)",
            "Mengenal tata krama dan sopan santun sesuai dengan nilai sosial budaya tempat"
    };

    public static String choices[][] = {
            {"Yes", "No"},

    };
    public static String kategori[] = {
            "Fisik Motorik",
            "Kognitif",
            "Bahasa",
            "Sosial Emosional"
    };

}
